---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: burnin-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  - secrets
  verbs:
  - get
- apiGroups:
  - burnin.glimmer.ai
  resources:
  - burninprofiles
  - burninsinks
  - burnintests
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - burnin.glimmer.ai
  resources:
  - burninruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - burnin.glimmer.ai
  resources:
  - burninruns/finalizers
  - burninschedules/finalizers
  verbs:
  - update
- apiGroups:
  - burnin.glimmer.ai
  resources:
  - burninruns/status
  - burninschedules/status
  - burninsinks/status
  - nodefingerprints/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - burnin.glimmer.ai
  resources:
  - burninschedules
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - burnin.glimmer.ai
  resources:
  - nodefingerprints
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
