// Code generated by go run ./hack/runnerlib. DO NOT EDIT.
//
// THIS FILE IS STAMPED INTO EVERY GO RUNNER, byte-identical, from
// hack/runnerlib/runnerlib.go.src. Edit the .src and run
//
//	go run ./hack/runnerlib
//
// to restamp; runners/runnerlib_test.go fails CI when a copy drifts or a
// runner re-declares one of these helpers locally.
//
// WHY A STAMP AND NOT A PACKAGE. Runner images build a throwaway module —
// `COPY *.go` + `go mod init` + GOPROXY=off, context runners/<name> — so a
// runner source file cannot import a repository package at all. Until that
// build idiom changes (a GEP-scale decision), sharing means copying, and the
// choice is between MANAGED copies with a guard and the divergence this repo
// already measured: the same three helpers hand-copied across seven runners,
// where the emitter that sanitized its values existed only in the one runner
// that had been burned (dcgm-diag), and the other six stayed raw.
//
// Not every runner uses every helper; .golangci.yml treats generated files
// laxly, which is why this header's first line matters.

package main

import (
	"fmt"
	"os"
	"strconv"
	"strings"
	"unicode/utf8"
)

// logf writes prose to stderr. Stdout belongs to the metric contract; a runner
// that narrates on stdout corrupts its own report.
func logf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
}

// sanitize keeps a value on one line. A metric value that contained a newline
// would be read by the parser as two lines, and the second one — a fragment of
// somebody's error string — would become the run's Message.
func sanitize(s string) string {
	s = strings.Map(func(r rune) rune {
		switch r {
		case '\n', '\r', '\t':
			return ' '
		}
		return r
	}, s)
	s = strings.Join(strings.Fields(s), " ")
	const max = 300
	if len(s) > max {
		// Cut on a rune boundary. DCGM's own prose is ASCII, but the reasons
		// this runner builds are not — they join with an em dash — and a byte
		// slice landing mid-sequence would put a replacement character into a
		// metric value, i.e. corrupt the very field a human reads to find out
		// why a node failed.
		cut := max
		for cut > 0 && !utf8.RuneStart(s[cut]) {
			cut--
		}
		s = s[:cut] + "…"
	}
	return s
}

// metric prints one key=value line on stdout — SANITIZED, always.
//
// The value is one runner bug away from carrying a newline (an error string,
// a kernel log excerpt), and a newline in a value splits the line: the tail
// becomes a bogus line the parser reads as the run's message, or worse, as a
// key nobody emitted. dcgm-diag learned this and grew sanitize(); the copied
// emitters in every other runner stayed `fmt.Printf` raw. The lesson lives
// here now so it cannot be un-learned per runner.
func metric(key, value string) {
	fmt.Printf("%s=%s\n", key, sanitize(value))
}

// envInt reads a positive integer from the environment, or falls back — and
// says so on stderr, because a silently substituted default turns a typo in a
// profile into a different test that reports under the intended test's name.
func envInt(name string, def int) int {
	v := strings.TrimSpace(os.Getenv(name))
	if v == "" {
		return def
	}
	n, err := strconv.Atoi(v)
	if err != nil || n <= 0 {
		logf("%s=%q is not a positive integer; using %d", name, v, def)
		return def
	}
	return n
}

// envOr reads a string from the environment, or falls back.
func envOr(key, fallback string) string {
	if v := strings.TrimSpace(os.Getenv(key)); v != "" {
		return v
	}
	return fallback
}
