// SPDX-License-Identifier: Apache-2.0
// Copyright the Glimmer authors.

package runners

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// THE STAMP GUARD. hack/runnerlib/runnerlib.go.src is stamped into every Go
// runner as zz_runnerlib.go, because the runner image build — a throwaway
// module with GOPROXY=off — cannot import a repository package. Copying is the
// only sharing available, so the copies are MANAGED: byte-identical to the
// source, regenerated with `go run ./hack/runnerlib`, and the helpers may not
// be re-declared locally.
//
// The history this guards against is measured, not hypothetical: the same
// three helpers were hand-copied across seven runners, and the emitter that
// sanitized its values existed only in the one runner that had been burned by
// a newline in a value (dcgm-diag). The other six stayed raw for a release.
// A lesson learned per-runner is a lesson the next runner un-learns.

const runnerlibSrc = "../hack/runnerlib/runnerlib.go.src"

// stampedHelpers are the declarations the stamp owns. A runner declaring one
// locally is divergence returning, whatever the body says.
var stampedHelpers = []string{"logf", "metric", "envInt", "envOr", "sanitize"}

func TestEveryGoRunnerCarriesAnIdenticalRunnerlibStamp(t *testing.T) {
	src, err := os.ReadFile(runnerlibSrc)
	if err != nil {
		t.Fatalf("the stamp source is missing: %v", err)
	}
	if !strings.HasPrefix(string(src), "// Code generated by") {
		t.Errorf("%s must begin with the canonical generated-file marker; .golangci.yml's "+
			"generated:lax is what excuses helpers a given runner does not use", runnerlibSrc)
	}

	stamped := 0
	for _, dir := range runnerDirs(t) {
		if !dirHasGoSources(t, dir) {
			continue
		}
		stamped++
		got, err := os.ReadFile(filepath.Join(dir, "zz_runnerlib.go"))
		if err != nil {
			t.Errorf("runners/%s has Go sources but no zz_runnerlib.go — run `go run ./hack/runnerlib` "+
				"from the repository root", dir)
			continue
		}
		if string(got) != string(src) {
			t.Errorf("runners/%s/zz_runnerlib.go differs from %s — it was edited in place, or the "+
				"source moved without a restamp. Run `go run ./hack/runnerlib`; the stamp is the one "+
				"file in a runner directory that is never edited by hand", dir, runnerlibSrc)
		}
	}
	if stamped == 0 {
		t.Fatal("no Go runner directories found; the guard checked nothing")
	}
}

func TestNoRunnerRedeclaresAStampedHelper(t *testing.T) {
	decl := regexp.MustCompile(`(?m)^func (` + strings.Join(stampedHelpers, "|") + `)\(`)
	for _, dir := range runnerDirs(t) {
		files, err := filepath.Glob(filepath.Join(dir, "*.go"))
		if err != nil {
			t.Fatal(err)
		}
		for _, f := range files {
			base := filepath.Base(f)
			if base == "zz_runnerlib.go" || strings.HasSuffix(base, "_test.go") {
				continue
			}
			src, err := os.ReadFile(f)
			if err != nil {
				t.Fatal(err)
			}
			for _, m := range decl.FindAllStringSubmatch(string(src), -1) {
				t.Errorf("runners/%s/%s declares %s locally; that helper is owned by the stamp "+
					"(hack/runnerlib/runnerlib.go.src). A local copy is how the sanitizing emitter "+
					"stayed in one runner while six others printed raw — edit the source and restamp "+
					"instead", dir, base, m[1])
			}
		}
	}
}

func dirHasGoSources(t *testing.T, dir string) bool {
	t.Helper()
	files, err := filepath.Glob(filepath.Join(dir, "*.go"))
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range files {
		base := filepath.Base(f)
		if !strings.HasSuffix(base, "_test.go") && base != "zz_runnerlib.go" {
			return true
		}
	}
	return false
}
